hendrikmuhs/ccache-action

src/restore.ts
This slows down the build and seems unnecessary.
=> Avoid updating the apt cache

action.yml
In the case of ccache, just because a build fails is not a reason not to save the cache. The intermediate cached data is still very useful for speeding up the following build which hopefully fixes the build failure.
=> Always save ccache, even on build failure

dist/restore/index.js, dist/save/index.js, src/save.ts
Currently I think that all the calls to `getExecBashOutput` are commands that are supposed to be parsed by the action (for example `ccache --help` to determine if ccache supports verbosity)
I think the output of theses commands should not be visible to the users. (For example, currently, the post run of the action shows the stats twice, and the --help flag of ccache)
=> Silent execution of getExecBashOutput

src/restore.ts
As mentioned in #88, ccache has made updates to further support the Windows environment. This bumps the version used to 4.7 which has the latest fixes.
=> [windows] Update ccache to 4.7

.github/workflows/tests.yml, action.yml, dist/restore/index.js, dist/save/index.js, src/restore.ts, src/save.ts
Prompted by #117.
For Github repositories with many different actions and concurrent PRs, `ccache-action`'s timestamps can quickly fill up the cache and evict other cached entries. This PR adds an option to disable timestamping. 
I am not familiar with either Javascript or Github Actions, so suggestions on how to improve this are very much welcome.
=> Make cache key timestamping optional.

dist/restore/index.js, src/restore.ts
I was having a specific problem with sccache on MSVC (it was reporting multiple files on the command line when there weren't). Turns out this has been fixed upstream, which I've confirmed in my fork. Maybe worth updating? Thanks.
=> Update sccache version to 0.3.3

dist/restore/index.js, src/restore.ts
This is not as nice as installing it ourselves, but this isn't that easy to do in general, while giving a message explaining what needs to be done is pretty simple, so do at least this.
See #131.
=> Give a clear error message if ccache can't be installed

.github/workflows/tests.yml, dist/restore/index.js, src/restore.ts
Fix #131
Also fix `bash` is not present on some slim Ubuntu/Debian Docker images nor on Alpine by default. `sh` in contrast is present on almost any platform.
CI should be passing, tested inside my fork.
=> Add Alpine (apk package manager) native install support

dist/restore/index.js, src/restore.ts
This PR updates `sccache` on Windows and Linux from 0.3.3 to 0.5.3, since there were some fixes and new features since (e.g. MSVC response file support). Homebrew has 0.5.3 on macOS as well.
=> Update `sccache` to 0.5.3

src/restore.ts
This addresses issue where GitHub actions runners report different mtime for compiler causing incorrect cache misses
=> Fix #146: use compiler hash instead of volatile mtime

.github/workflows/tests.yml, README.md, action.yml, dist/restore/index.js, src/restore.ts
It is an optional flag, so it should not break existing usages.
**Why this PR work?**
References:
- https://ccache.dev/manual/4.8.3.html#_run_modes
- https://github.com/ccache/ccache/blob/master/doc/INSTALL.md#installation
- https://reactnative.dev/docs/build-speed#local-caches
These links above all point out that we can use a symlink to let ccache override the default compilers.
=> Add a new flag `create-symlink`

dist/restore/index.js, src/restore.ts
Update sccache to 0.7.4 which contains a couple of important fixes for Windows.
=> deps(sccache): bump sccache

dist/restore/index.js, src/restore.ts
This action installs sccache under $USERPROFILE/.cargo/bin. GitHub runner images already have $USERPROFILE/.cargo/bin in the PATH, but self-hosted runners may not. This PR makes this action update the user's PATH to include the installation directory. This allows self-hosted runners to find sccache and prevents breakages in the unlikely event that a different installation directory is chosen in the future.
Note: I recently closed a duplicate PR with the intention of merging from a different fork but it is easier to merge from kendalharland:main
=> Add sccache to PATH after installation

.github/workflows/tests.yml, dist/restore/index.js, dist/save/index.js, src/common.ts, src/restore.ts, src/save.ts
Currently, if environment variables are set for CCACHE_DIR or SCCACHE_DIR then this action will ignore them and hardcode its own.
This is a problem if CCACHE_DIR is set for example in a docker file environment which is very hard to eliminate 
Fixes #96 
I think this is a better solution than #165 as that one still suffers from an invalid operation if either of the environment variables are set.
=> Make ccache-action respect environment variables

.github/workflows/tests.yml, __tests__/common.test.ts, __tests__/save.test.ts, action.yml, dist/restore/index.js, dist/save/index.js, src/common.ts, src/restore.ts, src/save.ts
uses the `--evict-older-than` option to evict any files from the cache that were not used during the job run. This prevents the cache from growing indefinitely as otherwise old files from previously restored caches are never deleted.
For a test I performed the following - 
1. [Built CMake 3.30.6](https://github.com/planetmarshall/ccache-action/actions/runs/12339373031)
* `evictOldFiles=true` - cache Size 39Mb
*  `evictOldFiles=false` - cache Size 39Mb
2. Then [Built CMake 3.31.2](https://github.com/planetmarshall/ccache-action/actions/runs/12339423977/attempts/1), reusing the cache from 1. Minimal cache hits in both cases due to change in sources.
* `evictOldFiles=true` - cache Size 39Mb
*  `evictOldFiles=false` - cache Size 78Mb
3. Then [Built CMake …
=> Evict old files from the cache prior to saving

src/restore.ts
When running this action inside a container as a non-root user, installing sccache will typically fail due to the non-root user not having write permissions to /usr/local/bin. This patch fixes this by using sudo for downloading/installing sccache along with some modifications to executeShellSudo so that it will execute the entire command as expected.
=> Use sudo (if available) when installing sccache

.github/workflows/tests.yml, dist/restore/index.js, src/restore.ts
Enable the `sccache` variant of  `ccache-action` to run on GitHub Ubuntu arm64 runners.
GitHub now supports a public preview of Ubuntu on arm64 runners, [announced last week](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/). The new runners can be used by anyone on any public repo.
The current implementation of `cccache-action` unconditionally downloads the Linux x86_64 `sccache` package when using the `sccache` variant. This package is incompatible with the arm runners.
NOTE: The `ccache` variant already works correctly on the arm runners because it installs `ccache` via the system's package manager.
Updated test workflow to run tests on `ubuntu-24.04-arm` and verify they pass …
=> support Ubuntu arm64 runners with sccache variant

dist/restore/index.js, src/restore.ts
If we aren't saving the cache we can get a small performance improvement by not writing new cache files during a build.
=> set cache to readonly if skipping save

dist/restore/index.js, src/restore.ts
Updates sccache to `v0.10.0` instead of `v0.7.6`. 
Pretty much the same change in https://github.com/hendrikmuhs/ccache-action/pull/314, except with updated hashes
=> Update sccache version to v0.10.0

.github/workflows/tests.yml, dist/restore/index.js, src/restore.ts
The main root issue is that the directory `${process.env.USERPROFILE}\\.cargo\\bin` doesn't exist beforehand, and isn't included in `$PATH`. Due to minor inconsistencies between the ccache/sccache cases, this issue had slightly different symptoms.
Fixes #317.
=> Fix installing on windows/ARM64

action.yml
"M" shouldn't cause any errors, but just to be consistent with officially documented supported suffixes in https://ccache.dev/manual/4.12.html
=> Use 'MB' in max-size default instead of 'M'
